version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: increase

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    versioning-strategy: increase
