<?php
/**
 * Copyright © Qliro AB. All rights reserved.
 * See LICENSE.txt for license details.
 */
/**
 * @var $block \Qliro\QliroOne\Block\Info\QliroOne
 */
?>
<div class="order-payment-method-name"><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>
    <?php if ($block->showWarning()): ?>
        <span style="color:red;"><?php echo $block->escapeHtml($block->getWarningText()); ?></span>
    <?php endif; ?>
</div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?php echo $block->escapeHtml(__('Qliro Order Id')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getQliroOrderId()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Qliro Reference')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getQliroReference()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Payment Method')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getQliroMethodName()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Payment Method Code')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getQliroMethod()); ?></td>
    </tr>
</table>
